wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712985419.0
    t:
      1:
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.16.6
      8:
      - 5
      13: darwin-x86_64
